concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-check
jobs:
  check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Checkout Extension SDK
      run: 'git clone https://github.com/hivemq/hivemq-extension-sdk.git ../hivemq-extension-sdk

        cd ../hivemq-extension-sdk

        git checkout ${GITHUB_REF##*/} || true

        cd ../hivemq-community-edition

        '
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Check
      run: ./gradlew test license forbiddenApis javadoc hivemqZip
name: CI Check
on:
  repository_dispatch:
    types: trigger-ga___check.yml
